name: home_sense
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  firebase_auth: ^5.3.4
  provider: ^6.1.2
  geolocator: ^13.0.2
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_img.jpg
    - assets/images/sala_img.jpg
    - assets/images/cozinha_img.jpg
    - assets/images/banheiro_img.jpg
    - assets/images/quarto_img.jpg
    - assets/images/externo_img.jpg
    - assets/images/garagem_img.jpg
    - assets/images/icon.png

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/icon.png
  android_12:
    image: assets/images/icon.png
    color: "#42a5f5"
    icon_background_color: "#111111"
    branding: assets/images/icon.png
  android: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/icon.png"
