name: home_sense
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  firebase_auth: ^5.3.4
  provider: ^6.1.2
  geolocator: ^13.0.2
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.3
  material_design_icons_flutter: ^7.0.7296
  flutter_colorpicker: ^1.1.0
  smooth_page_indicator: ^1.2.0+3
  animate_do: ^3.3.4
  firebase_messaging: ^15.1.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_img.jpg
    - assets/images/sala_img.jpg
    - assets/images/cozinha_img.jpg
    - assets/images/banheiro_img.jpg
    - assets/images/quarto_img.jpg
    - assets/images/externo_img.jpg
    - assets/images/garagem_img.jpg
    - assets/images/chegada_img.jpg
    - assets/images/saida_img.jpg
    - assets/images/avatar.png
    - assets/icon.png
    - assets/banner.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/banner.png

  # Configuração específica para Android 12+
  android_12:
    image: assets/banner.png
    color: "#ffffff"

  # Configuração para Android
  android: true
  android_gravity: fill


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#5F8F3C"
